// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	"github.com/skillvault/api/internal/biz"
	"github.com/skillvault/api/internal/conf"
	"github.com/skillvault/api/internal/data"
	"github.com/skillvault/api/internal/server"
	"github.com/skillvault/api/internal/service"
)

func wireApp(confServer *conf.Server, confData *conf.Data, confAuth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}

	authConfig := data.NewAuthConfig(confAuth)

	userRepo := data.NewUserRepo(dataData, logger)
	organizationRepo := data.NewOrganizationRepo(dataData, logger)
	orgMemberRepo := data.NewOrgMemberRepo(dataData, logger)
	skillRepo := data.NewSkillRepo(dataData, logger)
	skillVersionRepo := data.NewSkillVersionRepo(dataData, logger)
	scanResultRepo := data.NewScanResultRepo(dataData, logger)
	apiTokenRepo := data.NewAPITokenRepo(dataData, logger)
	auditLogRepo := data.NewAuditLogRepo(dataData, logger)
	cacheRepo := data.NewCacheRepo(dataData, logger)
	objectStorageRepo := data.NewObjectStorageRepo(dataData, logger)
	scanQueueRepo := data.NewScanQueueRepo(dataData, logger)

	authUsecase := biz.NewAuthUsecase(userRepo, cacheRepo, authConfig, logger)
	skillUsecase := biz.NewSkillUsecase(skillRepo, organizationRepo, orgMemberRepo, cacheRepo, logger)
	organizationUsecase := biz.NewOrganizationUsecase(organizationRepo, orgMemberRepo, cacheRepo, logger)
	versionUsecase := biz.NewVersionUsecase(skillVersionRepo, skillRepo, organizationRepo, orgMemberRepo, scanResultRepo, objectStorageRepo, scanQueueRepo, cacheRepo, logger)
	auditUsecase := biz.NewAuditUsecase(auditLogRepo, logger)
	tokenUsecase := biz.NewTokenUsecase(apiTokenRepo, logger)

	svc := service.NewSkillVaultService(authUsecase, skillUsecase, organizationUsecase, versionUsecase, auditUsecase, tokenUsecase)

	httpServer := server.NewHTTPServer(confServer, confAuth, apiTokenRepo, svc, logger)
	grpcServer := server.NewGRPCServer(confServer, confAuth, apiTokenRepo, logger)

	app := newApp(logger, httpServer, grpcServer)
	return app, cleanup, nil
}
